(WIP) New mobile menu
ProboCI/probo-docs pull request #21
Opened 2017-01-06 20:08 UTC by jkaeser

I want a Probo build.

2017-02-09 21:44 UTC, tortillaj requested changes

2017-02-09 21:44 UTC, tortillaj commented on Gemfile
> +   gem 'rake-jekyll', '1.1.0'
I don't think rake-jekyll and rack-jekyll are needed anymore. May need to test building the Jekyll site to be sure. They were added to enable deployment to GH pages, but we're not doing that anymore.

2017-02-09 21:44 UTC, tortillaj commented on _stylesheets/01-utilities/_variables.scss
> +$old-header-height: 60px;
Is this needed?

2017-02-09 21:44 UTC, tortillaj commented on _stylesheets/02-atoms/_containers.scss
> +		display: none;
Weird alignment in this file. Unless Github is acting up.

2017-02-09 21:44 UTC, tortillaj commented on _stylesheets/04-organisms/_section_landing.scss
> +  }
I detest empty Sass blocks :(

2017-02-09 21:44 UTC, tortillaj commented on javascripts/src/mobile-nav.js
> +  }
I added this toggleMenu method to simplify things. As a result, the implementation back in `probo.js` is simpler.

Doesn't need a change, just wanted to point it out.

2017-02-09 21:44 UTC, tortillaj commented on gulpfile.js
> -        beautify: true
Removing this setting lets the JS fully minify. Just pointing out the change I made.

2017-02-09 21:49 UTC, jkaeser reviewed
Moved this comment elsewhere.

2017-02-09 21:50 UTC, jkaeser commented on javascripts/src/mobile-nav.js
> +  }
We will need to duplicate these changes in https://github.com/ProboCI/probo.ci/pull/166.

2017-02-09 21:51 UTC, tortillaj commented on javascripts/src/mobile-nav.js
> +  }
I'll do it real quick.

2017-02-10 20:35 UTC, tortillaj commented on _stylesheets/04-organisms/_section_landing.scss
> +  }
Removed.

2017-02-10 20:35 UTC, tortillaj commented on _stylesheets/02-atoms/_containers.scss
> +		display: none;
Re-aligned

2017-02-10 20:35 UTC, tortillaj commented on _stylesheets/01-utilities/_variables.scss
> +$old-header-height: 60px;
Deleted

2017-02-10 20:35 UTC, tortillaj commented on Gemfile
> +   gem 'rake-jekyll', '1.1.0'
Removed

2017-02-10 22:19 UTC, tortillaj approved these changes
LGTM 🌟 🌟 🌟 🌟 🌟 🌟 🌟 🌟 🌟 🌟 🌟 🌟 🌟 🌟 

🌟 🌟 🌟 🌟 🌟 🌟 🌟 🌟 🌟 🌟

2017-02-10 22:19 UTC, tortillaj commented on javascripts/src/mobile-nav.js
> +  }
That is done.

2017-02-10 22:23 UTC, merged