Adding a note about inheritance from LAMP plugin.
ProboCI/probo-docs pull request #84
Opened 2018-04-18 21:49 UTC by sk33lz

2018-04-23 15:03 UTC, jkaeser requested changes

2018-04-23 15:03 UTC, jkaeser commented on docs/plugins/drupal-plugin.md
> +The Probo Drupal plugin provides an easy way to set Drupal site configuration options in a Probo Build to quickly integrate a Drupal website's repository. To use the Probo Drupal plugin you must decl
This first sentence has become a run-on. Can you split that into two sentences, please?

2018-04-23 15:03 UTC, jkaeser commented on docs/plugins/drupal-plugin.md
> +The Probo Drupal plugin inherits all [Probo LAMP plugin](/plugins/lamp-plugin/) configuration options. This allows additional Probo Build steps in your `.probo.yaml` file to layer additional LAMP con
You use "additional" twice in the same sentence, which sounds a little funny.

"This allows ~additional~ **other** Probo Build steps in your `.probo.yaml` file to layer additional LAMP configuration options and commands on top of the Drupal site specific configuration."

2018-04-23 16:40 UTC, sk33lz commented
Updated text as per John's comments.

2018-04-23 17:34 UTC, sk33lz commented
I added the lamp recipe specific to Drupal to the bottom of the page here, and added an anchor similar to what I just did on the LAMP plugin page.

2018-04-26 17:01 UTC, jkaeser approved these changes

2018-04-26 17:50 UTC, merged